language: scala
scala:
- 2.11.7
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - build-essential
    - nodejs
    - npm
install:
- sh "$TRAVIS_BUILD_DIR/.travis-ci-bintray-credentials.sh"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sbt"
  - "$HOME/.ivy2"
  - "$HOME/.sbt/launchers/"
before_script:
- mkdir -p $HOME/.sbt/launchers/0.13.8/
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
script:
- "sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M clean coverage test"
- find $HOME/.sbt -name "*.lock" | xargs rm
after_success:
- sbt coveralls
- test ${TRAVIS_PULL_REQUEST} == "false" && test $TRAVIS_BRANCH == "master" && sbt
  publish
notifications:
  slack:
    secure: PtU8WrGwOkhyzaSlfUC+JkSZbwkhNQYFll4gWYueSxjC2EXCSo3GyWoZs3jlCmjVIhyiA32Wh/BduuGH6CUNbjqx+DQH+WYAgsO2/u2NtRPT87wP0DY0X9c7+OBIKZfnCsfIgWlYSrW3WKjiOFAZvu40ihgV/3ZUADF0n5UyUss=
env:
  global:
  - secure: Y7jhT9FPYThlUxOjp+acxKb3uQS11s3uF1TpAMmSE810rNE98IRAfLObynqkdjtggwmWNxjoRZYzQPdr/MyW2vVN4E9/LxDyL+66mKDVuLMUhFlynnGpmr6zgXNZmdUqdiLC+FHtSjyIViWoHll/RhaPrA6geZ+9u4vJiF9MNhI=
  - secure: Feq5tinvzkPRcEe+cu+xqzMEhYBexju7+iS2PIp8k0jVK3aB+etw+aA3yig8i6S/ZTppJvuFFJNTTkUAuM5jtEf6PhvM+ohFNOucECMWcMWf8WiFioSuY5zm9jmvXKwyEHuWIGmfmNVzobLpdpSkNXHcFhNQiYb7t5LMbjYdwnI=
